-- =============================================================================
-- SAMPLE / NEW TENANT DATABASE — Email management (manual run)
-- =============================================================================
-- Supabase SQL Editor does not support \include. Do this:
--   1) Run: migrations/20250418_create_email_management_tables.sql
--   2) Run: migrations/20250418_add_email_settings_page_permissions.sql
--   3) Run: migrations/20250419_email_outbound_channel_settings.sql
--   4) Run: migrations/20250420_suppliers_email_po_intro_html.sql
--   5) Run: migrations/20250421_order_status_email_notifications.sql
--   6) Run: migrations/20250421_add_order_status_notifications_page_permissions.sql
--   7) On ADMIN DB run: migrations/20250418_tenant_migration_list_email_settings.sql
--      then: migrations/20250419_tenant_migration_list_email_channel_settings.sql
--      then: migrations/20250420_tenant_migration_list_suppliers_po_intro_html.sql
--      then: migrations/20250421_tenant_migration_list_order_status_notifications.sql
-- =============================================================================
