import type { Category, CostItem } from "@/types"
import { getCategoryMap } from "@/lib/data/categories-store"

/** Szekció alapú K-tétel kód: BURK-1000, EP-BON-1001 */
export const AUTO_CUSTOM_PATTERN = /^[A-Z0-9]{2,8}-\d{4}$/

/** Régi globális formátum — migrálásra kerül */
export const LEGACY_YEAR_CUSTOM_PATTERN = /^K-\d{4}-\d{4}$/

const SEQUENCE_START = 1000

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
}

export function getCategoryNumberPrefix(
  categoryId: string,
  categories?: Record<string, Category>
): string {
  const map = categories ?? getCategoryMap()
  return map[categoryId]?.code ?? "K"
}

export function isAutoGeneratedCustomIdentifier(identifier: string): boolean {
  const id = identifier.trim()
  return AUTO_CUSTOM_PATTERN.test(id) || LEGACY_YEAR_CUSTOM_PATTERN.test(id)
}

export function isLegacyPlainCustomIdentifier(identifier: string): boolean {
  const normalized = identifier.trim().toLowerCase()
  return normalized === "k-tétel" || normalized === "k-tetel" || normalized === "k tétel"
}

export function getMaxSequenceForPrefix(items: CostItem[], prefix: string): number {
  const pattern = new RegExp(`^${escapeRegex(prefix)}-(\\d{4})$`)
  let max = 0
  for (const item of items) {
    const match = item.identifier.match(pattern)
    if (match) max = Math.max(max, Number(match[1]))
  }
  return max
}

export function formatSectionCustomIdentifier(prefix: string, seq: number): string {
  return `${prefix}-${String(seq).padStart(4, "0")}`
}

export function generateNextCustomIdentifier(
  existing: CostItem[],
  categoryId: string,
  categories?: Record<string, Category>
): string {
  const prefix = getCategoryNumberPrefix(categoryId, categories)
  const maxSeq = getMaxSequenceForPrefix(existing, prefix)
  const nextSeq = maxSeq < SEQUENCE_START ? SEQUENCE_START : maxSeq + 1
  return formatSectionCustomIdentifier(prefix, nextSeq)
}

function needsCustomIdentifierMigration(identifier: string): boolean {
  return (
    isLegacyPlainCustomIdentifier(identifier) ||
    LEGACY_YEAR_CUSTOM_PATTERN.test(identifier.trim())
  )
}

/** Régi „K-tétel” és K-év-XXXX kódok átnevezése szekció prefixre */
export function ensureCustomIdentifiers(items: CostItem[]): CostItem[] {
  const pool: CostItem[] = []
  let changed = false

  const result = items.map((item) => {
    if (!needsCustomIdentifierMigration(item.identifier)) {
      pool.push(item)
      return item
    }

    changed = true
    const identifier = generateNextCustomIdentifier(pool, item.categoryId)
    const updated = { ...item, identifier, isCustomItem: true }
    pool.push(updated)
    return updated
  })

  return changed ? result : items
}

export function resolveCustomIdentifier(
  input: { identifier?: string; isCustomItem?: boolean; categoryId?: string },
  existing: CostItem[],
  isNew: boolean,
  categories?: Record<string, Category>
): { identifier: string; isCustomItem: boolean } {
  const isCustom =
    input.isCustomItem ??
    (input.identifier ? isCustomItemFromIdentifier(input.identifier) : true)

  if (!isCustom) {
    return {
      identifier: input.identifier?.trim() ?? "",
      isCustomItem: false,
    }
  }

  if (
    !isNew &&
    input.identifier?.trim() &&
    !needsCustomIdentifierMigration(input.identifier)
  ) {
    return { identifier: input.identifier.trim(), isCustomItem: true }
  }

  const categoryId = input.categoryId ?? Object.keys(categories ?? getCategoryMap())[0] ?? ""
  return {
    identifier: generateNextCustomIdentifier(existing, categoryId, categories),
    isCustomItem: true,
  }
}

export function isCustomItemFromIdentifier(identifier: string): boolean {
  if (isAutoGeneratedCustomIdentifier(identifier)) return true
  if (isLegacyPlainCustomIdentifier(identifier)) return true
  return false
}

/** Ajánlat / PDF megjelenítés — egyedi tételeknél Excel szerint „K-tétel” */
export function getQuoteDisplayIdentifier(
  item: Pick<CostItem, "identifier" | "isCustomItem">
): string {
  return item.isCustomItem ? "K-tétel" : item.identifier
}

export function previewNextCustomIdentifier(
  existing: CostItem[],
  categoryId: string,
  categories?: Record<string, Category>
): string {
  return generateNextCustomIdentifier(existing, categoryId, categories)
}
