import type { Trade } from "@/types"
import type { TradeRecord } from "@/types/trade"
import { DEFAULT_TRADE_RECORDS, TRADE_CODES } from "@/lib/trades/constants"
import { getTradesListSync } from "@/lib/trades/trades-cache"
import {
  isAutoGeneratedCustomIdentifier,
  isLegacyPlainCustomIdentifier,
} from "@/lib/item-identifier"

/** @deprecated Használd a `useTradeOptions()` hookot kliens komponensekben */
export function listTradeOptions(): { id: Trade; label: string }[] {
  return getTradesListSync().map((t) => ({ id: t.code, label: t.name }))
}

/** Statikus fallback — szerver oldali kód, migráció */
export const TRADES: { id: Trade; label: string }[] = DEFAULT_TRADE_RECORDS.map((t) => ({
  id: t.code,
  label: t.name,
}))

export const tradeMap = Object.fromEntries(
  DEFAULT_TRADE_RECORDS.map((t) => [t.code, { id: t.code, label: t.name }])
) as Record<string, { id: Trade; label: string }>

export function getTradeLabel(trade: Trade | string, trades?: TradeRecord[]): string {
  const list = trades ?? getTradesListSync()
  return list.find((t) => t.code === trade)?.name ?? String(trade)
}

export function getTradeOrder(trades?: TradeRecord[]): Trade[] {
  const list = trades ?? getTradesListSync()
  return list.map((t) => t.code)
}

export { TRADE_CODES }

export function isCustomIdentifier(identifier: string): boolean {
  if (isAutoGeneratedCustomIdentifier(identifier)) return true
  if (isLegacyPlainCustomIdentifier(identifier)) return true
  return false
}
