import type { Trade } from "@/types"
import type { TradeRecord } from "@/types/trade"

/** A 017_trades_seed.sql-lel szinkronban tartandó teljes szakág-lista */
export const TRADE_CODES: Trade[] = [
  "elokeszites",
  "organizacio",
  "bontas",
  "foldmunka",
  "epitomester",
  "acs",
  "tetofedes",
  "badogozas",
  "vizszigeteles",
  "homlokzat",
  "allvanyozas",
  "gepeszet",
  "futes-hutes",
  "klima-szellozes",
  "gazszereles",
  "elektromos",
  "riaszto",
  "napelem",
  "szarazepites",
  "burkolas",
  "festes",
  "nyilaszaró",
  "arnyekolas",
  "asztalos",
  "lakatos",
  "terburkolas",
  "kertepites",
  "takaritas",
]

export const DEFAULT_TRADE_RECORDS: TradeRecord[] = [
  { id: "trade-elokeszites", orgId: "org-1", code: "elokeszites", name: "Előkészítés, tervezés, engedélyezés", sortOrder: 1 },
  { id: "trade-organizacio", orgId: "org-1", code: "organizacio", name: "Organizáció, felvonulás", sortOrder: 2 },
  { id: "trade-bontas", orgId: "org-1", code: "bontas", name: "Bontás", sortOrder: 3 },
  { id: "trade-foldmunka", orgId: "org-1", code: "foldmunka", name: "Földmunka, tereprendezés", sortOrder: 4 },
  { id: "trade-epitomester", orgId: "org-1", code: "epitomester", name: "Építőmesteri munkák", sortOrder: 5 },
  { id: "trade-acs", orgId: "org-1", code: "acs", name: "Ácsmunka, tetőszerkezet", sortOrder: 6 },
  { id: "trade-tetofedes", orgId: "org-1", code: "tetofedes", name: "Tetőfedés", sortOrder: 7 },
  { id: "trade-badogozas", orgId: "org-1", code: "badogozas", name: "Bádogozás", sortOrder: 8 },
  { id: "trade-vizszigeteles", orgId: "org-1", code: "vizszigeteles", name: "Vízszigetelés", sortOrder: 9 },
  { id: "trade-homlokzat", orgId: "org-1", code: "homlokzat", name: "Homlokzati hőszigetelés", sortOrder: 10 },
  { id: "trade-allvanyozas", orgId: "org-1", code: "allvanyozas", name: "Állványozás", sortOrder: 11 },
  { id: "trade-gepeszet", orgId: "org-1", code: "gepeszet", name: "Gépészet (víz, szennyvíz, szaniter)", sortOrder: 12 },
  { id: "trade-futes-hutes", orgId: "org-1", code: "futes-hutes", name: "Fűtés-hűtés (hőszivattyú, kazán)", sortOrder: 13 },
  { id: "trade-klima-szellozes", orgId: "org-1", code: "klima-szellozes", name: "Klíma, szellőzés", sortOrder: 14 },
  { id: "trade-gazszereles", orgId: "org-1", code: "gazszereles", name: "Gázszerelés", sortOrder: 15 },
  { id: "trade-elektromos", orgId: "org-1", code: "elektromos", name: "Elektromos (erősáram)", sortOrder: 16 },
  { id: "trade-riaszto", orgId: "org-1", code: "riaszto", name: "Gyengeáram (riasztó, kamera, hálózat)", sortOrder: 17 },
  { id: "trade-napelem", orgId: "org-1", code: "napelem", name: "Napelemes rendszer", sortOrder: 18 },
  { id: "trade-szarazepites", orgId: "org-1", code: "szarazepites", name: "Szárazépítés (gipszkarton)", sortOrder: 19 },
  { id: "trade-burkolas", orgId: "org-1", code: "burkolas", name: "Burkolás", sortOrder: 20 },
  { id: "trade-festes", orgId: "org-1", code: "festes", name: "Festés, mázolás, tapétázás", sortOrder: 21 },
  { id: "trade-nyilaszaró", orgId: "org-1", code: "nyilaszaró", name: "Nyílászáró", sortOrder: 22 },
  { id: "trade-arnyekolas", orgId: "org-1", code: "arnyekolas", name: "Árnyékolástechnika", sortOrder: 23 },
  { id: "trade-asztalos", orgId: "org-1", code: "asztalos", name: "Asztalosmunka, belsőépítészet", sortOrder: 24 },
  { id: "trade-lakatos", orgId: "org-1", code: "lakatos", name: "Lakatosmunka, fémszerkezet", sortOrder: 25 },
  { id: "trade-terburkolas", orgId: "org-1", code: "terburkolas", name: "Térburkolás, kerítés", sortOrder: 26 },
  { id: "trade-kertepites", orgId: "org-1", code: "kertepites", name: "Kertépítés, parképítés", sortOrder: 27 },
  { id: "trade-takaritas", orgId: "org-1", code: "takaritas", name: "Építés utáni takarítás", sortOrder: 28 },
]
